"""add_custom_style_fields

Revision ID: 0702fe33fe6c
Revises: a9962b0d350c
Create Date: 2026-05-16 21:28:40.016770

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0702fe33fe6c'
down_revision: str | Sequence[str] | None = 'a9962b0d350c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('custom_style_description', sa.Text(), nullable=True))
    op.add_column('novels', sa.Column('writing_style_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'writing_style_prompt')
    op.drop_column('novels', 'custom_style_description')
    # ### end Alembic commands ###
