"""add_volumes_table

Revision ID: 2001dedede3d
Revises: ad3a0f8b7114
Create Date: 2026-05-16 19:49:32.895157

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2001dedede3d'
down_revision: str | Sequence[str] | None = 'ad3a0f8b7114'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chapter_start', sa.Integer(), nullable=True),
    sa.Column('chapter_end', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumes_novel_id'), 'volumes', ['novel_id'], unique=False)
    op.add_column('chapters', sa.Column('volume_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'volume_number')
    op.drop_index(op.f('ix_volumes_novel_id'), table_name='volumes')
    op.drop_table('volumes')
    # ### end Alembic commands ###
