"""novel_project_schema

Revision ID: 31e0b7e83e73
Revises: e45b29ed4fe6
Create Date: 2026-05-16 15:46:28.803727

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31e0b7e83e73'
down_revision: str | Sequence[str] | None = 'e45b29ed4fe6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('novel_type', sa.String(length=50), nullable=False),
    sa.Column('target_words', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_novel_id'), 'novels', ['novel_id'], unique=True)
    op.create_index(op.f('ix_novels_status'), 'novels', ['status'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('background_story', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_novel_id'), 'characters', ['novel_id'], unique=False)
    op.create_table('power_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_systems_novel_id'), 'power_systems', ['novel_id'], unique=False)
    op.create_table('world_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id')
    )
    op.add_column('tasks', sa.Column('novel_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_novel_id'), 'tasks', ['novel_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'novels', ['novel_id'], ['novel_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_novel_id'), table_name='tasks')
    op.drop_column('tasks', 'novel_id')
    op.drop_table('world_settings')
    op.drop_index(op.f('ix_power_systems_novel_id'), table_name='power_systems')
    op.drop_table('power_systems')
    op.drop_index(op.f('ix_characters_novel_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_status'), table_name='novels')
    op.drop_index(op.f('ix_novels_novel_id'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
