"""add_storylines_arcs_scenes

Revision ID: 8795631f9b67
Revises: dc4e4f012739
Create Date: 2026-05-17 00:57:43.684561

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8795631f9b67'
down_revision: str | Sequence[str] | None = 'dc4e4f012739'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearances', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_table_novel_id'), 'scenes_table', ['novel_id'], unique=False)
    op.create_table('storylines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_events', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storylines_novel_id'), 'storylines', ['novel_id'], unique=False)
    op.create_table('character_arcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.String(length=100), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('arc_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_arcs_novel_id'), 'character_arcs', ['novel_id'], unique=False)
    op.create_table('storyline_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role_in_line', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyline_characters')
    op.drop_index(op.f('ix_character_arcs_novel_id'), table_name='character_arcs')
    op.drop_table('character_arcs')
    op.drop_index(op.f('ix_storylines_novel_id'), table_name='storylines')
    op.drop_table('storylines')
    op.drop_index(op.f('ix_scenes_table_novel_id'), table_name='scenes_table')
    op.drop_table('scenes_table')
    # ### end Alembic commands ###
