"""add_writing_style

Revision ID: ad3a0f8b7114
Revises: 31e0b7e83e73
Create Date: 2026-05-16 19:23:37.035524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3a0f8b7114'
down_revision: Union[str, Sequence[str], None] = '31e0b7e83e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('novels', sa.Column('writing_style', sa.String(length=50), nullable=False, server_default='现代白话'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'writing_style')
    # ### end Alembic commands ###
