"""add_message_confirmed_as

Revision ID: b0018a838516
Revises: 8795631f9b67
Create Date: 2026-05-17 05:51:18.196708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0018a838516'
down_revision: Union[str, Sequence[str], None] = '8795631f9b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('confirmed_as', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'confirmed_as')
    # ### end Alembic commands ###
